# This scan engine is used to import subdomains from a given list and scan them passively
# The fastest scan for retrieving a lot of informations on a given scope of urls
# QUICK SCAN - USE LESS RESOURCES - NO SUBDOMAIN RECOVERY - RECOMMENDED ON INITIAL SCAN

# Global vars for all tools
#
# Custom header - FFUF, Nuclei, Dalfox, CRL Fuzz, HTTPx, Fetch URL (Hakrawler, Katana, Gospider)
custom_header: {
  'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0',
}
# 'user_agent': ''                    # Dalfox only
# 'enable_http_crawl': true           # All tools
# 'timeout': 10                       # Subdomain discovery, Screenshot, Port scan, FFUF, Nuclei
# 'threads': 30                       # All tools
# 'rate_limit': 150                   # Port scan, FFUF, Nuclei
# 'intensity': 'normal'               # Screenshot (grab only the root endpoints of each subdomain), Nuclei (reduce number of endpoints to scan), OSINT (not implemented yet)
# 'retries': 1                        # Nuclei

http_crawl: {
  # 'custom_header': {
  #   'Cookie':'Test',
  #   'User-Agent': 'Mozilla/5.0'
  # },
  # 'threads': 30,
  # 'follow_redirect': false
}
osint: {
  'discover': [
      'emails',
      'metainfo',
      'employees'
    ],
  'dorks': [
    'login_pages',
    'admin_panels',
    'dashboard_pages',
    'stackoverflow',
    'social_media',
    'project_management',
    'code_sharing',
    'config_files',
    'jenkins',
    'wordpress_files',
    'php_error',
    'exposed_documents',
    'db_files',
    'git_exposed'
  ],
  # 'custom_dorks': [],
  'intensity': 'normal',
  'documents_limit': 50
}
waf_detection: {
  'enable_http_crawl': true
}
screenshot: {
  'enable_http_crawl': true,
  'intensity': 'normal',
  'timeout': 10,
  'threads': 40
}