# This scan engine is used to discover subdomains, scan them passively with screenshots and retrieve additional endpoints
# The most accurate scan between speed and efficiency as it retrieve a lot of informations on the target
# MEDIUM SPEED SCAN - USE SOME RESOURCES BUT LESS THAN ACTIVE SCAN - HIGHLY RECOMMENDED ON INITIAL SCAN

# Global vars for all tools
#
# Custom header - FFUF, Nuclei, Dalfox, CRL Fuzz, HTTPx, Fetch URL (Hakrawler, Katana, Gospider)
custom_header: {
  'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0',
}
# 'user_agent': ''                    # Dalfox only
# 'enable_http_crawl': true           # All tools
# 'timeout': 10                       # Subdomain discovery, Screenshot, Port scan, FFUF, Nuclei                       
# 'threads': 30                       # All tools
# 'rate_limit': 150                   # Port scan, FFUF, Nuclei
# 'intensity': 'normal'               # Screenshot (grab only the root endpoints of each subdomain), Nuclei (reduce number of endpoints to scan), OSINT (not implemented yet)
# 'retries': 1                        # Nuclei

subdomain_discovery: {
  'uses_tools': ['subfinder', 'ctfr', 'sublist3r', 'tlsx', 'oneforall', 'netlas'],  # amass-passive, amass-active, All
  'enable_http_crawl': true,
  'threads': 30,
  'timeout': 5,
  # 'use_subfinder_config': false,
  # 'use_amass_config': false,
  # 'amass_wordlist': 'deepmagic.com-prefixes-top50000'
}
http_crawl: {
  # 'custom_header': {
  #   'Cookie':'Test',
  #   'User-Agent': 'Mozilla/5.0'
  # },
  'threads': 10,
  # 'follow_redirect': false
}
osint: {
  'discover': [
      'emails',
      'metainfo',
      'employees'
    ],
#  'dorks': [
#    'login_pages',
#    'admin_panels',
#    'dashboard_pages',
#    'stackoverflow',
#    'social_media',
#    'project_management',
#    'code_sharing',
#    'config_files',
#    'jenkins',
#    'wordpress_files',
#    'php_error',
#    'exposed_documents',
#    'db_files',
#    'git_exposed'
#  ],
  # 'custom_dorks': [],
  'intensity': 'normal',
  'documents_limit': 50
}
waf_detection: {
  'enable_http_crawl': true
}
screenshot: {
  'enable_http_crawl': true,
  'intensity': 'normal',
  'timeout': 10,
  'threads': 40
}
fetch_url: {
  'uses_tools': ['gospider', 'hakrawler', 'waybackurls', 'katana', 'gau'],
  'remove_duplicate_endpoints': true,
  'duplicate_fields': ['content_length', 'page_title'],
  'enable_http_crawl': true,
  'gf_patterns': ['debug_logic', 'idor', 'interestingEXT', 'interestingparams', 'interestingsubs', 'lfi', 'rce', 'redirect', 'sqli', 'ssrf', 'ssti', 'xss'],
  'ignore_file_extensions': ['png', 'jpg', 'jpeg', 'gif', 'mp4', 'mpeg', 'mp3'],
  'threads': 30
}