"""
Shared helpers for DataTables-style list views (column maps, filter params, table config, actions).

CONTRACT (column_map, serializer, frontend):
- Column maps: api/helpers/datatables/column_maps.py. Keys are DataTables column indices as strings.
  Views use apply_datatables_order(qs, request, DATATABLE_COLUMN_MAP_XXX).
- Filter params and contexts: api/helpers/datatables/filters.py (FILTER_PARAM_*, FILTER_CONTEXT_*).
- Table config: api/helpers/datatables/table_config.py (TABLE_ID_*, get_datatable_table_config).
- When adding/moving/removing columns: update column map, serializer, and frontend columns array.

Consumer reference: see table_config.py and filters.py for view/template per TABLE_ID.
Filter select IDs (keys of FILTER_CONTEXT_*) must match the id attribute of <select> in filter partials.
Use validate_datatable_filter_config() or test_validate_datatable_filter_config_passes to catch drift.
"""

from .actions import get_datatable_action_urls
from .column_maps import (
    DATATABLE_COLUMN_MAP_DIRECTORY,
    DATATABLE_COLUMN_MAP_ENDPOINT,
    DATATABLE_COLUMN_MAP_ENDPOINT_CHANGES,
    DATATABLE_COLUMN_MAP_EXPLOIT,
    DATATABLE_COLUMN_MAP_INTERESTING_ENDPOINT,
    DATATABLE_COLUMN_MAP_INTERESTING_SUBDOMAIN,
    DATATABLE_COLUMN_MAP_IPS,
    DATATABLE_COLUMN_MAP_ORGANIZATIONS,
    DATATABLE_COLUMN_MAP_S3_BUCKETS,
    DATATABLE_COLUMN_MAP_SCAN_ENGINE,
    DATATABLE_COLUMN_MAP_SCAN_HISTORY,
    DATATABLE_COLUMN_MAP_SCHEDULED_SCANS,
    DATATABLE_COLUMN_MAP_SCOPES,
    DATATABLE_COLUMN_MAP_SECRET,
    DATATABLE_COLUMN_MAP_SUBDOMAIN,
    DATATABLE_COLUMN_MAP_SUBDOMAIN_CHANGES,
    DATATABLE_COLUMN_MAP_SUBSCAN_HISTORY,
    DATATABLE_COLUMN_MAP_TARGETS,
    DATATABLE_COLUMN_MAP_VULNERABILITY,
    DATATABLE_COLUMN_MAP_WORDLIST,
    DATATABLE_NULLS_LAST_FIELDS,
    apply_datatables_order,
    get_datatables_column_search_value,
    get_datatables_order_column,
)
from .filters import (
    FILTER_PARAM_BUCKET_NAME,
    FILTER_PARAM_ENGINE_NAME,
    FILTER_PARAM_HAS_SCAN,
    FILTER_PARAM_HTTP_STATUS,
    FILTER_PARAM_NAME,
    FILTER_PARAM_ORGANIZATION,
    FILTER_PARAM_PAGE_TITLE,
    FILTER_PARAM_SCAN_ENGINE,
    FILTER_PARAM_SCOPE,
    FILTER_PARAM_SCOPE_TYPE,
    FILTER_PARAM_SEVERITY,
    FILTER_PARAM_SOURCE,
    FILTER_PARAM_STATUS,
    FILTER_PARAM_SUBDOMAIN,
    FILTER_PARAM_TARGET,
    apply_filter_list_in,
    apply_filter_list_in_by_param,
    apply_filter_scan_status,
    apply_filter_scope_type,
    apply_filter_task_status,
    get_nuclei_severity_codes_for_labels,
    get_request_filter_list,
    get_scan_status_codes_for_labels,
    get_scan_status_filter_labels,
    get_scope_type_values_for_labels,
    get_task_status_codes_for_labels,
    get_task_status_filter_labels,
)
from .health import get_datatable_filter_warnings
from .table_config import (
    DATATABLE_TABLE_CONFIGS,
    EXPECTED_FILTER_PARAM_NAMES,
    EXPECTED_FILTER_SELECT_IDS,
    ROW_GROUP_COOKIE_SCAN_HISTORY,
    ROW_GROUP_COOKIE_SCOPE_LIST,
    ROW_GROUP_COOKIE_TARGETS,
    ROW_GROUP_COOKIE_VULNERABILITIES,
    ROW_GROUP_SELECTOR_SCAN_HISTORY,
    ROW_GROUP_SELECTOR_SCOPE,
    ROW_GROUP_SELECTOR_SUBDOMAIN,
    ROW_GROUP_SELECTOR_TARGET,
    ROW_GROUP_SELECTOR_VULN,
    TABLE_ID_ORGANIZATION_LIST,
    TABLE_ID_S3_BUCKETS,
    TABLE_ID_SCAN_ENGINE_LIST,
    TABLE_ID_SCAN_HISTORY,
    TABLE_ID_SCHEDULED_SCANS,
    TABLE_ID_SCOPE_LIST,
    TABLE_ID_SECRETS,
    TABLE_ID_SUBSCAN_HISTORY,
    TABLE_ID_TARGET_LIST,
    TABLE_ID_VULNERABILITIES,
    TABLE_ID_WORDLIST_LIST,
    get_datatable_row_group_config,
    get_datatable_table_config,
    validate_datatable_filter_config,
)


__all__ = [
    "apply_datatables_order",
    "apply_filter_list_in",
    "apply_filter_list_in_by_param",
    "apply_filter_scan_status",
    "apply_filter_scope_type",
    "apply_filter_task_status",
    "DATATABLE_COLUMN_MAP_DIRECTORY",
    "DATATABLE_COLUMN_MAP_ENDPOINT",
    "DATATABLE_COLUMN_MAP_ENDPOINT_CHANGES",
    "DATATABLE_COLUMN_MAP_EXPLOIT",
    "DATATABLE_COLUMN_MAP_INTERESTING_ENDPOINT",
    "DATATABLE_COLUMN_MAP_INTERESTING_SUBDOMAIN",
    "DATATABLE_COLUMN_MAP_IPS",
    "DATATABLE_COLUMN_MAP_ORGANIZATIONS",
    "DATATABLE_COLUMN_MAP_S3_BUCKETS",
    "DATATABLE_COLUMN_MAP_SCAN_ENGINE",
    "DATATABLE_COLUMN_MAP_SCAN_HISTORY",
    "DATATABLE_COLUMN_MAP_SCHEDULED_SCANS",
    "DATATABLE_COLUMN_MAP_SCOPES",
    "DATATABLE_COLUMN_MAP_SUBDOMAIN",
    "DATATABLE_COLUMN_MAP_SUBDOMAIN_CHANGES",
    "DATATABLE_COLUMN_MAP_SUBSCAN_HISTORY",
    "DATATABLE_COLUMN_MAP_TARGETS",
    "DATATABLE_COLUMN_MAP_VULNERABILITY",
    "DATATABLE_COLUMN_MAP_SECRET",
    "DATATABLE_COLUMN_MAP_WORDLIST",
    "DATATABLE_NULLS_LAST_FIELDS",
    "DATATABLE_TABLE_CONFIGS",
    "EXPECTED_FILTER_PARAM_NAMES",
    "EXPECTED_FILTER_SELECT_IDS",
    "FILTER_PARAM_BUCKET_NAME",
    "FILTER_PARAM_ENGINE_NAME",
    "FILTER_PARAM_HAS_SCAN",
    "FILTER_PARAM_HTTP_STATUS",
    "FILTER_PARAM_NAME",
    "FILTER_PARAM_ORGANIZATION",
    "FILTER_PARAM_PAGE_TITLE",
    "FILTER_PARAM_SCOPE",
    "FILTER_PARAM_SCOPE_TYPE",
    "FILTER_PARAM_SCAN_ENGINE",
    "FILTER_PARAM_SEVERITY",
    "FILTER_PARAM_SOURCE",
    "FILTER_PARAM_STATUS",
    "FILTER_PARAM_SUBDOMAIN",
    "FILTER_PARAM_TARGET",
    "get_datatable_action_urls",
    "get_datatable_filter_warnings",
    "get_datatable_row_group_config",
    "get_datatable_table_config",
    "get_datatables_column_search_value",
    "get_datatables_order_column",
    "get_nuclei_severity_codes_for_labels",
    "get_request_filter_list",
    "get_scan_status_codes_for_labels",
    "get_scan_status_filter_labels",
    "get_scope_type_values_for_labels",
    "get_task_status_codes_for_labels",
    "get_task_status_filter_labels",
    "ROW_GROUP_COOKIE_SCAN_HISTORY",
    "ROW_GROUP_COOKIE_SCOPE_LIST",
    "ROW_GROUP_COOKIE_TARGETS",
    "ROW_GROUP_COOKIE_VULNERABILITIES",
    "ROW_GROUP_SELECTOR_SCAN_HISTORY",
    "ROW_GROUP_SELECTOR_SCOPE",
    "ROW_GROUP_SELECTOR_SUBDOMAIN",
    "ROW_GROUP_SELECTOR_TARGET",
    "ROW_GROUP_SELECTOR_VULN",
    "TABLE_ID_ORGANIZATION_LIST",
    "TABLE_ID_S3_BUCKETS",
    "TABLE_ID_SCAN_ENGINE_LIST",
    "TABLE_ID_SCAN_HISTORY",
    "TABLE_ID_SCHEDULED_SCANS",
    "TABLE_ID_SCOPE_LIST",
    "TABLE_ID_SECRETS",
    "TABLE_ID_SUBSCAN_HISTORY",
    "TABLE_ID_TARGET_LIST",
    "TABLE_ID_VULNERABILITIES",
    "TABLE_ID_WORDLIST_LIST",
    "validate_datatable_filter_config",
]
