# Generated by Django 3.2.4 on 2022-02-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0004_rename_template_used_vulnerability_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipaddress",
            name="subscan",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.subscan"
            ),
        ),
    ]
