# Generated by Django 3.2.25 on 2025-02-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0057_auto_20231201_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ports',
            field=models.ManyToManyField(db_index=True, related_name='ports', to='startScan.Port'),
        ),
    ]
