# Generated by Django 3.2.25 on 2025-02-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0058_alter_ipaddress_ports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='ports',
        ),
        migrations.AddField(
            model_name='port',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='startScan.ipaddress'),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('ip_address', 'number')},
        ),
    ]
