# Generated by Django 3.2.25 on 2025-07-10 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0062_vulnerabilityreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='async_task_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1),
        ),
    ]
