# Generated by Django 3.2.25 on 2025-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0064_delete_vulnerabilityreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_status',
            field=models.IntegerField(
    choices=[
        (-1, "Pending"),
        (0, "Queued"),
        (1, "Running"),
        (2, "Completed"),
        (3, "Failed"),
        (4, "Running Background"),
    ],
    default=-1
),
        ),
    ]
