# Generated by Django 3.2.25 on 2025-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0066_move_screenshot_to_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='results_dir',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
