# Generated by Django 3.2.25 on 2025-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0067_extend_field_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directoryfile',
            unique_together={('name', 'url', 'http_status')},
        ),
        migrations.AddIndex(
            model_name='directoryfile',
            index=models.Index(fields=['name', 'url'], name='startScan_d_name_3c4265_idx'),
        ),
        migrations.AddIndex(
            model_name='directoryfile',
            index=models.Index(fields=['http_status'], name='startScan_d_http_st_43c970_idx'),
        ),
    ]
