# Generated by Django 5.2.6 on 2025-10-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0069_add_legacy_scan_flag"),
        ("targetApp", "0042_domain_custom_dns_servers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="discovered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="endpoint",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.endpoint"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="scan_history",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.scanhistory"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="site_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="subdomain",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.subdomain"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="target_domain",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="targetApp.domain"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="url",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="username",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="Exploit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1000)),
                ("exploit_id", models.CharField(blank=True, max_length=200, null=True)),
                ("provider", models.CharField(blank=True, max_length=200, null=True)),
                ("matched_at", models.CharField(blank=True, max_length=10000, null=True)),
                ("reference", models.CharField(blank=True, max_length=10000, null=True)),
                ("discovered_date", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("cve_ids", models.ManyToManyField(blank=True, related_name="exploit_cves", to="startScan.cveid")),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.endpoint"
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.ipaddress"
                    ),
                ),
                (
                    "scan_history",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.scanhistory"
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.subdomain"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="exploit_tags", to="startScan.vulnerabilitytags"),
                ),
                (
                    "target_domain",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="targetApp.domain"
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_date", "name"],
            },
        ),
    ]
