# Generated by Django 5.2.6 on 2025-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0070_employee_discovered_date_employee_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.AddField(
            model_name="employee",
            name="emails",
            field=models.ManyToManyField(blank=True, related_name="employees", to="startScan.email"),
        ),
    ]
