# Generated by Django 5.2.6 on 2025-12-31 02:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0072_secatorrunner"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="headers",
            field=models.JSONField(
                blank=True, help_text="HTTP headers (response_headers and request_headers)", null=True
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="lines",
            field=models.IntegerField(blank=True, default=0, help_text="Number of lines in the response", null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="method",
            field=models.CharField(blank=True, help_text="HTTP method: GET, POST, etc.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="words",
            field=models.IntegerField(blank=True, default=0, help_text="Number of words in the response", null=True),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="alive",
            field=models.BooleanField(
                blank=True, default=False, help_text="Whether the IP address is alive", null=True
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="cpes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                help_text="List of CPEs (Common Platform Enumeration)",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="host",
            field=models.CharField(
                blank=True, help_text="Hostname associated with this port", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="protocol",
            field=models.CharField(blank=True, help_text="Protocol: TCP, UDP", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="port",
            name="state",
            field=models.CharField(
                blank=True, help_text="Port state: OPEN, CLOSED, FILTERED", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="List of sources that discovered this subdomain",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="subdomain",
            name="verified",
            field=models.BooleanField(
                blank=True, default=False, help_text="Whether the subdomain is verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="category",
            field=models.CharField(blank=True, help_text="Tag category from Secator", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="stored_response_path",
            field=models.CharField(blank=True, help_text="Path to stored response file", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="value",
            field=models.CharField(blank=True, help_text="Tag value from Secator", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="confidence_nb",
            field=models.IntegerField(blank=True, default=0, help_text="Confidence as integer", null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="cvss_vec",
            field=models.CharField(blank=True, help_text="CVSS vector string", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="epss_score",
            field=models.FloatField(blank=True, help_text="EPSS (Exploit Prediction Scoring System) score", null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="ip",
            field=models.CharField(
                blank=True, help_text="IP address where vulnerability was found", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="reference",
            field=models.CharField(blank=True, help_text="Reference URL or identifier", max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="severity_nb",
            field=models.IntegerField(blank=True, default=0, help_text="Severity as integer", null=True),
        ),
    ]
