# Generated by Django 5.2.6 on 2025-12-31 02:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0073_add_secator_fields"),
        ("targetApp", "0044_add_extra_data_to_domaininfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddress",
            name="alive",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="cpes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="port",
            name="host",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="protocol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="subdomain",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="subdomain",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="stored_response_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="value",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="confidence_nb",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="cvss_vec",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="epss_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="ip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="reference",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="severity_nb",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("host", models.CharField(help_text="Hostname for the certificate", max_length=1000)),
                (
                    "fingerprint_sha256",
                    models.CharField(
                        blank=True, help_text="SHA256 fingerprint of the certificate", max_length=64, null=True
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, help_text="IP address where certificate was found", max_length=100, null=True
                    ),
                ),
                ("raw_value", models.TextField(blank=True, help_text="Raw certificate value", null=True)),
                (
                    "subject_cn",
                    models.CharField(blank=True, help_text="Subject Common Name", max_length=500, null=True),
                ),
                (
                    "subject_an",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        help_text="Subject Alternative Names",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(blank=True, help_text="Certificate validity start date", null=True),
                ),
                ("not_after", models.DateTimeField(blank=True, help_text="Certificate validity end date", null=True)),
                (
                    "issuer_dn",
                    models.CharField(blank=True, help_text="Issuer Distinguished Name", max_length=1000, null=True),
                ),
                ("issuer_cn", models.CharField(blank=True, help_text="Issuer Common Name", max_length=500, null=True)),
                ("issuer", models.CharField(blank=True, help_text="Issuer name", max_length=500, null=True)),
                (
                    "self_signed",
                    models.BooleanField(
                        blank=True, default=False, help_text="Whether the certificate is self-signed", null=True
                    ),
                ),
                (
                    "trusted",
                    models.BooleanField(
                        blank=True, default=False, help_text="Whether the certificate is trusted", null=True
                    ),
                ),
                ("status", models.CharField(blank=True, help_text="Certificate status", max_length=50, null=True)),
                ("keysize", models.IntegerField(blank=True, help_text="Certificate key size in bits", null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, help_text="Certificate serial number", max_length=200, null=True),
                ),
                (
                    "ciphers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        help_text="Supported ciphers",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "discovered_date",
                    models.DateTimeField(auto_now_add=True, help_text="Date when certificate was discovered"),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="targetApp.domain"
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.ipaddress"
                    ),
                ),
                (
                    "scan_history",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.scanhistory"
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="startScan.subdomain"
                    ),
                ),
            ],
            options={
                "db_table": "certificate",
                "ordering": ["-discovered_date"],
                "unique_together": {("host", "fingerprint_sha256", "scan_history")},
            },
        ),
    ]
