# Generated by Django 5.2.6 on 2026-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0078_add_port_confidence_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipaddress",
            name="protocol",
            field=models.CharField(blank=True, help_text="IP protocol: IPv4 or IPv6", max_length=10, null=True),
        ),
    ]
