# Generated by Django 5.2.6 on 2026-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0079_add_ip_protocol_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="scan_type",
            field=models.CharField(blank=True, help_text="Scan type from run_opts.scan_type", max_length=50, null=True),
        ),
    ]
