# Generated by Django 5.2.6 on 2026-01-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0019_remove_alias_from_secator_scan"),
        ("startScan", "0081_alter_endpoint_confidence_alter_ipaddress_protocol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanhistory",
            name="scan_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="scanEngine.enginetype"
            ),
        ),
    ]
