# Generated by Django 5.2.6 on 2026-01-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0082_make_scan_type_nullable"),
    ]

    operations = [
        # Step 1: Add celery_id to SecatorRunner
        migrations.AddField(
            model_name="secatorrunner",
            name="celery_id",
            field=models.CharField(blank=True, help_text="Celery task ID for this runner", max_length=100, null=True),
        ),
        # Step 2: Add runner_id to ScanActivity (nullable, no data migration needed)
        migrations.AddField(
            model_name="scanactivity",
            name="runner_id",
            field=models.ForeignKey(
                blank=True,
                help_text="SecatorRunner associated with this activity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="startScan.secatorrunner",
            ),
        ),
        # Step 3: Remove old celery_id from ScanActivity
        migrations.RemoveField(
            model_name="scanactivity",
            name="celery_id",
        ),
        # Step 4: Remove celery_ids from ScanHistory and SubScan
        migrations.RemoveField(
            model_name="scanhistory",
            name="celery_ids",
        ),
        migrations.RemoveField(
            model_name="subscan",
            name="celery_ids",
        ),
    ]
