# Generated by Django 5.2.6 on 2026-01-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0083_add_celery_id_to_runner"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatorrunner",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Status from Secator (RUNNING, SUCCESS, FAILURE, REVOKED, etc.)",
                max_length=50,
                null=True,
            ),
        ),
    ]
