# Generated by Django 5.2.6 on 2026-02-04

from django.conf import settings
import django.contrib.postgres.fields.array
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0001_initial"),
        ("targetApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("startScan", "0089_add_secator_runner_workspace_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "imported_subdomains",
                    django.contrib.postgres.fields.array.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "out_of_scope_subdomains",
                    django.contrib.postgres.fields.array.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "schedule_mode",
                    models.CharField(
                        choices=[("periodic", "Periodic"), ("clocked", "One-off (clocked)")],
                        default="periodic",
                        max_length=20,
                    ),
                ),
                ("frequency_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "frequency_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(db_index=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_run_count", models.PositiveIntegerField(default=0)),
                ("one_off", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="targetApp.domain"),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="scanEngine.enginetype"),
                ),
            ],
            options={
                "db_table": "scan_schedule",
                "ordering": ["next_run"],
            },
        ),
    ]
