# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0090_add_scan_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanschedule",
            name="secator_kwargs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="scan_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scanEngine.enginetype",
            ),
        ),
    ]
