# Generated by Django 5.2.6

import django.contrib.postgres.fields.array
from django.db import migrations, models


def backfill_null_arrays_to_empty(apps, schema_editor):
    """Set NULL imported_subdomains/out_of_scope_subdomains to [] before adding NOT NULL."""
    ScanSchedule = apps.get_model("startScan", "ScanSchedule")
    ScanSchedule.objects.filter(imported_subdomains__isnull=True).update(imported_subdomains=[])
    ScanSchedule.objects.filter(out_of_scope_subdomains__isnull=True).update(out_of_scope_subdomains=[])


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0091_scan_schedule_secator_kwargs"),
    ]

    operations = [
        migrations.RunPython(backfill_null_arrays_to_empty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="scanschedule",
            name="imported_subdomains",
            field=django.contrib.postgres.fields.array.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="out_of_scope_subdomains",
            field=django.contrib.postgres.fields.array.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
