# Generated by Django 5.2.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_null_initiated_by(apps, schema_editor):
    """Set NULL initiated_by to first available user so we can add NOT NULL."""
    ScanSchedule = apps.get_model("startScan", "ScanSchedule")
    null_count = ScanSchedule.objects.filter(initiated_by__isnull=True).count()
    if null_count == 0:
        return
    User = apps.get_model(settings.AUTH_USER_MODEL)
    fallback_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if fallback_user is None:
        raise ValueError(
            "Cannot backfill ScanSchedule.initiated_by: no user in database. "
            "Create a user or fix NULL initiated_by_id rows before migrating."
        )
    ScanSchedule.objects.filter(initiated_by__isnull=True).update(initiated_by=fallback_user)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("startScan", "0092_scanschedule_arrayfields_not_null"),
    ]

    operations = [
        migrations.RunPython(backfill_null_initiated_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="scanschedule",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
