# Generated by Django 5.2.6 on 2026-02-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0093_scanschedule_initiated_by_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanschedule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
