# Generated by Django 5.2.6 on 2026-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0026_secatorworker"),
        ("startScan", "0095_secatorrunner_worker_fk"),
        ("targetApp", "0048_fix_on_delete_constraints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="command",
            index=models.Index(fields=["scan_history_id", "name", "time"], name="startScan_c_scan_hi_3a5c4a_idx"),
        ),
        migrations.AddIndex(
            model_name="scanactivity",
            index=models.Index(fields=["scan_of_id", "status"], name="startScan_s_scan_of_3c4d7a_idx"),
        ),
        migrations.AddIndex(
            model_name="scanactivity",
            index=models.Index(fields=["scan_of_id", "runner_id", "time"], name="startScan_s_scan_of_c9bdd4_idx"),
        ),
        migrations.AddIndex(
            model_name="secatorrunner",
            index=models.Index(fields=["scan_history_id", "runner_type"], name="startScan_s_scan_hi_a578c6_idx"),
        ),
        migrations.AddIndex(
            model_name="subscan",
            index=models.Index(fields=["scan_history_id", "status"], name="startScan_s_scan_hi_5c36dc_idx"),
        ),
        migrations.AddIndex(
            model_name="subdomain",
            index=models.Index(fields=["scan_history_id", "content_length"], name="ss_sub_scan_content_len"),
        ),
        migrations.AddIndex(
            model_name="endpoint",
            index=models.Index(fields=["scan_history_id", "content_length"], name="ss_ep_scan_content_len"),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["scan_history_id", "cvss_score"], name="ss_vuln_scan_cvss_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["scan_history_id", "severity"], name="ss_vuln_scan_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="secatorrunner",
            index=models.Index(
                fields=["scan_history_id", "runner_type", "-created_at"],
                name="ss_runner_scan_type_created",
            ),
        ),
        migrations.AddIndex(
            model_name="secatorrunner",
            index=models.Index(
                fields=["scan_history_id", "-created_at"],
                name="ss_runner_scan_created",
            ),
        ),
    ]
