# Generated by Django 5.2.6 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Replace ss_runner_scan_created with a covering index (INCLUDE) so that
    queries filtering by scan_history_id and ordering by created_at DESC
    can use an index scan; runner_data is excluded from INCLUDE to stay
    under PostgreSQL's 8191-byte index row limit.
    """

    dependencies = [
        ("startScan", "0096_add_secator_sync_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="secatorrunner",
            name="ss_runner_scan_created",
        ),
        migrations.AddIndex(
            model_name="secatorrunner",
            index=models.Index(
                fields=["scan_history_id", "-created_at"],
                name="ss_runner_scan_created_cov",
                include=[
                    "id",
                    "runner_type",
                    "runner_name",
                    "workspace_name",
                    "domain_id",
                    "worker_id",
                    "celery_id",
                    "status",
                    "updated_at",
                ],
            ),
        ),
    ]
