# Generated by Django 5.2.6 on 2026-02-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0098_perf_indexes_subscan_todonote_vulnerability"),
        ("targetApp", "0050_backfill_target_from_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanhistory",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_histories",
                to="targetApp.target",
            ),
        ),
    ]
