# Generated by Django 5.2.6 on 2026-03-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("startScan", "0122_secator_finding_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdomain",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                related_name="technologies",
                through="startScan.SubdomainTechnology",
                to="startScan.technology",
            ),
        ),
        migrations.AlterField(
            model_name="subdomaintechnology",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
