# Generated by Django 5.2.6 on 2025-10-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_userapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapikey",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="System keys cannot be deleted through the UI and are managed by reNgine internally",
            ),
        ),
    ]
