name: 🛠️ CI/CD
description: File a feature request or bug-report for CI/CD
title: "ci(scope): "
labels: ["ci"]
body:
- type: textarea
  attributes:
    label: Expected feature
    description: A clear and concise description of what the problem is and how it could be approached.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternative solutions
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  id: acknowledgements
  attributes:
    label: Acknowledgements
    description: Your bug report will be closed if you don't follow the checklist below.
    options:
      - label: This issue is not a duplicate of an existing bug report.
        required: true
      - label: I have chosen an appropriate title.
        required: true
      - label: All requested information has been provided properly.
        required: true
