services:
  db:
    build: ./postgres

  redis:
    build: ./redis

  celery:
    build:
      context: ./celery
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}

  web:
    build:
      context: ./web
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}

  proxy:
    build: ./proxy

  ollama:
    build: ./ollama