"""
Target type constants. Single source of truth for Target.target_type values.
Used by Target model choices and by views, services, and API when comparing or creating targets.
"""

TARGET_TYPE_HOST = "host"
TARGET_TYPE_HOST_PORT = "host:port"
TARGET_TYPE_IP = "ip"
TARGET_TYPE_CIDR_RANGE = "cidr_range"
TARGET_TYPE_URL = "url"
TARGET_TYPE_EMAIL = "email"
TARGET_TYPE_ORG_NAME = "org_name"
TARGET_TYPE_USERNAME = "username"
TARGET_TYPE_FILENAME = "filename"
TARGET_TYPE_PORT = "port"
TARGET_TYPE_SLUG = "slug"
TARGET_TYPE_STR = "str"

TARGET_TYPE_CHOICES = [
    (TARGET_TYPE_HOST, TARGET_TYPE_HOST),
    (TARGET_TYPE_HOST_PORT, TARGET_TYPE_HOST_PORT),
    (TARGET_TYPE_IP, TARGET_TYPE_IP),
    (TARGET_TYPE_CIDR_RANGE, TARGET_TYPE_CIDR_RANGE),
    (TARGET_TYPE_URL, TARGET_TYPE_URL),
    (TARGET_TYPE_EMAIL, TARGET_TYPE_EMAIL),
    (TARGET_TYPE_ORG_NAME, TARGET_TYPE_ORG_NAME),
    (TARGET_TYPE_USERNAME, TARGET_TYPE_USERNAME),
    (TARGET_TYPE_FILENAME, TARGET_TYPE_FILENAME),
    (TARGET_TYPE_PORT, TARGET_TYPE_PORT),
    (TARGET_TYPE_SLUG, TARGET_TYPE_SLUG),
    (TARGET_TYPE_STR, TARGET_TYPE_STR),
]

# Exposed to JS as window.RENGINE_TARGET_TYPES (e.g. RENGINE_TARGET_TYPES.HOST === "host").
RENGINE_TARGET_TYPES_FOR_JS = {
    "CIDR_RANGE": TARGET_TYPE_CIDR_RANGE,
    "EMAIL": TARGET_TYPE_EMAIL,
    "FILENAME": TARGET_TYPE_FILENAME,
    "HOST": TARGET_TYPE_HOST,
    "HOST_PORT": TARGET_TYPE_HOST_PORT,
    "IP": TARGET_TYPE_IP,
    "ORG_NAME": TARGET_TYPE_ORG_NAME,
    "PORT": TARGET_TYPE_PORT,
    "SLUG": TARGET_TYPE_SLUG,
    "STR": TARGET_TYPE_STR,
    "URL": TARGET_TYPE_URL,
    "USERNAME": TARGET_TYPE_USERNAME,
}
