# Generated by Django 5.2.6 on 2025-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0041_organization_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="custom_dns_servers",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
