# Generated by Django 5.2.6 on 2025-12-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0043_add_secator_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaininfo",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
