# Generated by Django 5.2.6 on 2026-01-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0044_add_extra_data_to_domaininfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainregistration",
            name="contact",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="domainregistration",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registrar",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="registrar",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registrar",
            name="fax",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
