# Generated by Django 5.2.6 on 2026-01-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0045_add_fields_to_domain_registration_and_registrar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.TextField(),
        ),
    ]
