# Generated by Django 5.2.6 on 2026-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0046_change_dnsrecord_name_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrecord",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
