# Generated by Django 5.2.6 on 2026-02-16 20:59
#
# Migration order and recovery: see wiki install-migrations.md.
# Dev notes: Introduce Target model and Domain.target_id (targetApp).
# - Before: Domain (targetApp) had project_id only; no Target model.
# - This migration: creates Target (value, target_type, project, ...); adds nullable target_id FK on Domain.
# - Upgrade path: run 0049 first. Then 0050 backfills Target per Domain and domain.target_id; 0051 moves domain tables to startScan.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_user_preference"),
        ("targetApp", "0048_fix_on_delete_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=2000)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("host", "host"),
                            ("host:port", "host:port"),
                            ("ip", "ip"),
                            ("cidr_range", "cidr_range"),
                            ("url", "url"),
                            ("email", "email"),
                            ("org_name", "org_name"),
                            ("username", "username"),
                            ("filename", "filename"),
                            ("port", "port"),
                            ("slug", "slug"),
                            ("str", "str"),
                        ],
                        max_length=50,
                    ),
                ),
                ("port", models.CharField(blank=True, max_length=20, null=True)),
                ("custom_dns_servers", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("h1_team_handle", models.CharField(blank=True, max_length=100, null=True)),
                ("insert_date", models.DateTimeField(null=True)),
                ("start_scan_date", models.DateTimeField(blank=True, null=True)),
                ("request_headers", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dashboard.project"),
                ),
            ],
            options={
                "ordering": ["-insert_date"],
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domain_set",
                to="targetApp.target",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="targets",
            field=models.ManyToManyField(blank=True, related_name="organizations", to="targetApp.target"),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("project_id", "value", "target_type"), name="targetApp_target_project_value_type_uniq"
            ),
        ),
    ]
