# Generated by Django 5.2.6 on 2026-02-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0027_add_scanengine_audit_indexes"),
        ("targetApp", "0051_move_domain_tables_to_startscan"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="scan_config_override",
            field=models.JSONField(
                blank=True,
                help_text="Per-target scan parameter overrides (threads, rate_limit, timeout, etc.)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Scope",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("program_bug_bounty", "Bug Bounty Program"),
                            ("engagement_internal", "Internal Engagement"),
                            ("engagement_external", "External Engagement"),
                            ("engagement_osint", "OSINT Engagement"),
                            ("engagement_red_team", "Red Team Engagement"),
                            ("engagement_other", "Other Engagement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("threads", models.PositiveIntegerField(blank=True, null=True)),
                ("rate_limit", models.PositiveIntegerField(blank=True, help_text="Requests per second", null=True)),
                ("timeout", models.PositiveIntegerField(blank=True, help_text="HTTP timeout in seconds", null=True)),
                ("retries", models.PositiveIntegerField(blank=True, null=True)),
                ("delay", models.FloatField(blank=True, help_text="Delay between requests in seconds", null=True)),
                ("proxy", models.CharField(blank=True, max_length=500, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("request_headers", models.JSONField(blank=True, help_text="Key-value HTTP headers", null=True)),
                ("follow_redirect", models.BooleanField(blank=True, null=True)),
                ("depth", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "default_profiles",
                    models.JSONField(
                        blank=True,
                        help_text="List of Secator profile names (speed, evasion, general, network, or custom)",
                        null=True,
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        help_text="Advanced options (method, data, wordlist, ports, match/filter regex, etc.)",
                        null=True,
                    ),
                ),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scopes", to="targetApp.organization"
                    ),
                ),
                ("targets", models.ManyToManyField(blank=True, related_name="scopes", to="targetApp.target")),
                ("workers", models.ManyToManyField(blank=True, related_name="scopes", to="scanEngine.secatorworker")),
            ],
            options={
                "ordering": ["-insert_date"],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "name"), name="targetapp_scope_org_name_uniq")
                ],
            },
        ),
    ]
