# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0052_scope_and_target_scan_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="default_profiles",
            field=models.JSONField(
                blank=True,
                help_text="JSON object mapping category (speed, evasion, general, network) to profile name",
                null=True,
            ),
        ),
    ]
