# Generated by Django 5.2.6 on 2026-02-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0054_note_normalize_scope_default_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="request_headers",
            field=models.JSONField(
                blank=True,
                help_text='Optional HTTP headers as a JSON object, e.g. {"X-Api-Key": "secret"}. Must be a valid JSON object.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="request_headers",
            field=models.JSONField(
                blank=True,
                help_text='Optional HTTP headers as a JSON object, e.g. {"X-Api-Key": "secret"}. Must be a valid JSON object.',
                null=True,
            ),
        ),
    ]
