# Generated by Django 5.2.6 on 2026-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("targetApp", "0056_uniformize_scan_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="scan_config",
            field=models.JSONField(blank=True, help_text="Per-target scan parameter overrides and profiles", null=True),
        ),
    ]
