# Generated by Django 3.2.25 on 2025-08-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0007_lark_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilityreportsetting',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityreportsetting',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
