# Generated by Django 5.2.6 on 2025-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0008_extend_field_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="enginetype",
            name="scan_type",
            field=models.CharField(
                choices=[("internet", "Internet"), ("internal_network", "Internal Network")],
                default="internet",
                help_text="Type of scan this engine is designed for",
                max_length=20,
            ),
        ),
    ]
