# Generated by Django 5.2.6 on 2025-10-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0009_enginetype_scan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanEngine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("default_engine", models.BooleanField(default=False, null=True)),
                (
                    "yaml_config",
                    models.TextField(blank=True, help_text="Legacy YAML configuration for the scan engine.", null=True),
                ),
                (
                    "secator_workflow_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bug_bounty_basic", "Bug Bounty Basic"),
                            ("internal_network_basic", "Internal Network Basic"),
                            ("vulnerability_assessment", "Vulnerability Assessment"),
                            ("custom", "Custom Workflow"),
                        ],
                        help_text="Name of the predefined Secator workflow to use.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "custom_secator_workflow_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload a custom Secator workflow YAML file.",
                        null=True,
                        upload_to="secator_workflows/",
                    ),
                ),
                (
                    "workflow_mode",
                    models.CharField(
                        choices=[
                            ("legacy", "Legacy YAML (ancien système)"),
                            ("secator", "Secator Workflow (nouveau système)"),
                        ],
                        default="legacy",
                        help_text="Determines whether to use legacy YAML or Secator workflow.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scan Engine",
                "verbose_name_plural": "Scan Engines",
                "ordering": ["name"],
            },
        ),
    ]
