# Generated by Django 5.2.6 on 2025-10-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0009_enginetype_scan_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecatorWorkflow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("custom", "Custom")],
                        default="custom",
                        help_text="Type of workflow: built-in from Secator or custom",
                        max_length=20,
                    ),
                ),
                ("yaml_configuration", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("internet", "Internet"), ("internal_network", "Internal Network")],
                        default="internet",
                        help_text="Type of scan this workflow is designed for",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="installedexternaltool",
            name="is_legacy",
            field=models.BooleanField(
                default=True, help_text="Whether this is a legacy scan engine (deprecated in favor of Secator)"
            ),
        ),
        migrations.CreateModel(
            name="SecatorTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "task_type",
                    models.CharField(help_text="Secator task type (e.g., subfinder, nuclei)", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_builtin", models.BooleanField(default=False, help_text="Whether this is a built-in Secator task")),
                ("yaml_configuration", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("name", "task_type")},
            },
        ),
        migrations.CreateModel(
            name="SecatorScan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("internet", "Internet"), ("internal_network", "Internal Network")],
                        default="internet",
                        help_text="Type of scan this configuration is designed for",
                        max_length=20,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("workflow", "Workflow"), ("tasks", "Individual Tasks")],
                        default="workflow",
                        help_text="Whether to run a workflow or individual tasks",
                        max_length=20,
                    ),
                ),
                (
                    "scan_config_type",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("custom", "Custom")],
                        default="custom",
                        help_text="Type of scan configuration: built-in or custom",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Individual Secator tasks to run (if execution_mode is 'tasks')",
                        to="scanEngine.secatortask",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secator workflow to use (if execution_mode is 'workflow')",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scanEngine.secatorworkflow",
                    ),
                ),
            ],
        ),
    ]
