# Generated by Django 5.2.6 on 2025-10-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0010_scanengine"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanengine",
            name="secator_builtin_workflow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cidr_recon", "CIDR Reconnaissance"),
                    ("code_scan", "Code Vulnerability Scan"),
                    ("host_recon", "Host Reconnaissance"),
                    ("subdomain_recon", "Subdomain Discovery"),
                    ("url_bypass", "URL Bypass"),
                    ("url_crawl", "URL Crawl (Fast)"),
                    ("url_dirsearch", "URL Directory Search"),
                    ("url_fuzz", "URL Fuzz (Slow)"),
                    ("url_params_fuzz", "URL Parameters Fuzz"),
                    ("url_vuln", "URL Vulnerability Scan"),
                    ("user_hunt", "User Account Search"),
                    ("wordpress", "WordPress Vulnerability Scan"),
                ],
                help_text="Name of the Secator built-in workflow to use.",
                max_length=100,
                null=True,
            ),
        ),
    ]
