# Generated by Django 5.2.6 on 2025-10-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0014_remove_installed_external_tool"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secatorscan",
            name="execution_mode",
        ),
        migrations.RemoveField(
            model_name="secatorscan",
            name="secator_scan_type",
        ),
        migrations.RemoveField(
            model_name="secatorscan",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="secatorscan",
            name="workflow",
        ),
        migrations.AddField(
            model_name="secatorscan",
            name="alias",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domain", "Domain Scan"),
                    ("host", "Host Scan"),
                    ("network", "Internal Network Scan"),
                    ("subdomain", "Subdomain Scan"),
                    ("url", "URL Scan"),
                ],
                help_text="Built-in scan alias from Secator",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="secatorscan",
            name="yaml_configuration",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="secatorscan",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="secatorscan",
            name="scan_config_type",
            field=models.CharField(
                choices=[("builtin", "Built-in"), ("custom", "Custom")],
                default="builtin",
                help_text="Type of scan configuration: built-in or custom",
                max_length=20,
            ),
        ),
    ]
