# Generated by Django 5.2.6 on 2025-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0015_refactor_secatorscan_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatorworkflow",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="User-friendly display name for the workflow", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="secatorworkflow",
            name="alias",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cidr_recon", "CIDR Recon"),
                    ("code_scan", "Code Scan"),
                    ("domain_recon", "Domain Recon"),
                    ("host_recon", "Host Recon"),
                    ("subdomain_recon", "Subdomain Recon"),
                    ("url_bypass", "URL Bypass"),
                    ("url_crawl", "URL Crawl"),
                    ("url_dirsearch", "URL Directory Search"),
                    ("url_fuzz", "URL Fuzz"),
                    ("url_params_fuzz", "URL Parameters Fuzz"),
                    ("url_vuln", "URL Vulnerability"),
                    ("user_hunt", "User Hunt"),
                    ("wordpress", "WordPress"),
                ],
                help_text="Built-in workflow alias from Secator",
                max_length=50,
                null=True,
            ),
        ),
    ]
