# Generated by Django 5.2.6 on 2026-01-03 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0018_secatorscan_long_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secatorscan",
            name="alias",
        ),
    ]
