# Generated by Django 5.2.6 on 2026-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0019_remove_alias_from_secator_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecatorProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("speed", "Speed"),
                            ("evasion", "Evasion"),
                            ("general", "General"),
                            ("network", "Network"),
                        ],
                        help_text="Category of the profile",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(help_text="Description of the profile")),
                (
                    "enforce",
                    models.BooleanField(
                        default=False, help_text="Whether this profile should enforce its options (handled by Secator)"
                    ),
                ),
                ("opts", models.TextField(help_text="YAML configuration options for the profile")),
                (
                    "profile_type",
                    models.CharField(
                        choices=[("builtin", "Built-in"), ("custom", "Custom")],
                        default="custom",
                        help_text="Type of profile: built-in from Secator or custom",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this profile is available for use")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["profile_type", "category", "name"],
            },
        ),
    ]
