# Generated by Django 5.2.6 on 2026-01-12 18:52

from django.db import migrations, models


def set_initial_defaults(apps, schema_editor):
    """Set initial default profiles: polite (speed), stealth (evasion), full (general), all_ports (network)"""
    SecatorProfile = apps.get_model("scanEngine", "SecatorProfile")

    default_profiles = {
        "speed": "polite",
        "evasion": "stealth",
        "general": "full",
        "network": "all_ports",
    }

    for category, profile_name in default_profiles.items():
        try:
            profile = SecatorProfile.objects.get(name=profile_name, category=category)
            # Only set default if no default already exists for this category
            if not SecatorProfile.objects.filter(category=category, is_default=True).exists():
                profile.is_default = True
                profile.save(update_fields=["is_default"])
        except SecatorProfile.DoesNotExist:
            # Profile doesn't exist yet, skip
            pass


def reverse_set_initial_defaults(apps, schema_editor):
    """Reverse: unset all defaults"""
    SecatorProfile = apps.get_model("scanEngine", "SecatorProfile")
    SecatorProfile.objects.filter(is_default=True).update(is_default=False)


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0020_secatorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatorprofile",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this profile is the default for its category (only one default per category allowed)",
            ),
        ),
        migrations.AddConstraint(
            model_name="secatorprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("category",),
                name="unique_default_per_category",
            ),
        ),
        migrations.RunPython(set_initial_defaults, reverse_set_initial_defaults),
    ]
