# Generated by Django - SecatorTask: replace category with tags (ArrayField)

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def category_to_tags(apps, schema_editor):
    """Convert existing category string to tags list (e.g. url/fuzz -> [url, fuzz])."""
    SecatorTask = apps.get_model("scanEngine", "SecatorTask")
    batch_size = 1000
    to_update = []
    for task in SecatorTask.objects.only("id", "category", "tags").iterator():
        if not task.category:
            continue
        task.tags = [t.strip() for t in task.category.split("/") if t.strip()]
        to_update.append(task)
        if len(to_update) >= batch_size:
            SecatorTask.objects.bulk_update(to_update, ["tags"])
            to_update = []
    if to_update:
        SecatorTask.objects.bulk_update(to_update, ["tags"])


def tags_to_category(apps, schema_editor):
    """Revert: build category from tags (joined by /)."""
    SecatorTask = apps.get_model("scanEngine", "SecatorTask")
    batch_size = 1000
    to_update = []
    for task in SecatorTask.objects.only("id", "tags", "category").iterator():
        if not task.tags:
            continue
        task.category = "/".join(task.tags)
        to_update.append(task)
        if len(to_update) >= batch_size:
            SecatorTask.objects.bulk_update(to_update, ["category"])
            to_update = []
    if to_update:
        SecatorTask.objects.bulk_update(to_update, ["category"])


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0021_add_secatorprofile_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatortask",
            name="tags",
            field=ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                help_text="Secator task tags for filtering and grouping (e.g. url, fuzz, dns)",
                size=None,
            ),
            preserve_default=True,
        ),
        migrations.RunPython(category_to_tags, tags_to_category),
        migrations.RemoveField(
            model_name="secatortask",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="secatortask",
            options={"ordering": ["name"]},
        ),
    ]
