# Generated by Django - SecatorWorkflow: add tags (ArrayField)

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0022_secatortask_tags_replace_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatorworkflow",
            name="tags",
            field=ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                blank=True,
                default=list,
                help_text="Secator workflow tags for filtering and grouping (e.g. http, recon, fuzz)",
                size=None,
            ),
        ),
    ]
