# Generated by Django - SecatorScan: add workflow_identifiers for DB-side filtering

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0023_secatorworkflow_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="secatorscan",
            name="workflow_identifiers",
            field=ArrayField(
                base_field=models.CharField(blank=True, max_length=255),
                blank=True,
                default=list,
                help_text="Denormalized list of workflow identifiers (aliases/names) from YAML for DB-side filtering.",
                size=None,
            ),
        ),
    ]
