# Generated by Django 5.2.6 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0025_backfill_secatorscan_workflow_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecatorWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ssh_host", models.CharField(max_length=255)),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("ssh_user", models.CharField(max_length=255)),
                (
                    "ssh_auth_type",
                    models.CharField(
                        choices=[("key", "SSH key"), ("password", "Password")],
                        default="key",
                        max_length=20,
                    ),
                ),
                ("ssh_key_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("ssh_password_encrypted", models.TextField(blank=True, null=True)),
                ("deploy_path", models.CharField(max_length=1024)),
                ("container_name", models.CharField(blank=True, max_length=255, null=True)),
                ("api_reachable", models.BooleanField(default=False)),
                ("last_status_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ssh_ok", models.BooleanField(default=False)),
                ("container_running", models.BooleanField(default=False)),
                (
                    "api_access_type",
                    models.CharField(
                        choices=[
                            ("tunnel", "SSH tunnel"),
                            ("classic", "HTTPS (external URL)"),
                        ],
                        default="classic",
                        max_length=20,
                    ),
                ),
                (
                    "api_tunnel_port",
                    models.PositiveIntegerField(
                        default=8443,
                        help_text="Port on worker side (127.0.0.1:port) when using SSH tunnel.",
                    ),
                ),
                (
                    "api_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL of reNgine API (e.g. https://rengine.example.com) for classic access.",
                        max_length=512,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
