# Generated by Django 5.2.6 on 2026-03-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanEngine", "0030_rename_scan_swq_worker_stat_cr_scanengine__worker__bda119_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secatorworkerqueuedcommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("timed_out", "Timed out"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
