name: Docker Image CI

on:
  pull_request:
    paths:
      - 'docker/**'
  push:
    branches:
      - "master"
      - "release/**"
    paths:
      - 'docker/**'
    tags:
      - "v*.*.*"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to registry'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

env:
  REGISTRY: ghcr.io
  OWNER: security-tools-alliance
  PROJECT: rengine-ng

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: [celery, web, postgres, redis, ollama, certs, proxy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION=$(cat web/reNgine/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.PROJECT }}
          tags: |
            type=ref,event=branch,enable=${{ !contains(github.ref, 'release/') }}
            type=ref,event=pr
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=v${{ steps.get_version.outputs.version }},enable=${{ contains(github.ref, 'release/') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          flavor: |
            prefix=rengine-${{ matrix.image }}-,onlatest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        if: github.event_name != 'pull_request' || github.event.inputs.push_image == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.image }}
          file: ./docker/${{ matrix.image }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' || github.event.inputs.push_image == 'true' }}
          build-args: |
            HOST_UID=1000
            HOST_GID=1000
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

  update-release:
    needs: build-and-push
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update release description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | \
            jq -r .id)
          
          images="celery web postgres redis ollama certs proxy"
          image_list=""
          for image in $images; do
            image_list="${image_list}- ghcr.io/${{ env.OWNER }}/${{ env.PROJECT }}:rengine-${image}-${{ github.ref_name }}\n"
          done
          
          body="Docker images for this release:\n${image_list}"
          
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${release_id}" \
            -d "{\"body\": \"$body\"}"
