"""
Shared constants for Secator worker pull-agent authentication.

This module is imported by both:
- the Django server code (API endpoints that accept pull-agent requests)
- the worker-side pull agent (bundled and executed on the worker host)
"""

PULL_TOKEN_HEADER = "X-Rengine-Worker-Pull-Token"

# Shared pull-agent environment variable names (server + worker script).
ENV_PULL_COMMAND_RETENTION_SECONDS = "RENGINE_PULL_COMMAND_RETENTION_SECONDS"
ENV_PULL_REVOKE_WAIT_SECONDS = "RENGINE_PULL_REVOKE_WAIT_SECONDS"
ENV_PULL_COMMAND_POLL_INTERVAL_MIN_SECONDS = "RENGINE_PULL_COMMAND_POLL_INTERVAL_MIN_SECONDS"
ENV_PULL_COMMAND_POLL_INTERVAL_MAX_SECONDS = "RENGINE_PULL_COMMAND_POLL_INTERVAL_MAX_SECONDS"
ENV_PULL_COMMAND_POLL_JITTER_RATIO = "RENGINE_PULL_COMMAND_POLL_JITTER_RATIO"
ENV_PULL_TOKEN_MAX_LENGTH = "RENGINE_PULL_TOKEN_MAX_LENGTH"

ENV_PULL_AGENT_ENABLED = "RENGINE_PULL_AGENT_ENABLED"
ENV_PULL_API_BASE_URL = "RENGINE_PULL_API_BASE_URL"
ENV_PULL_WORKER_ID = "RENGINE_WORKER_ID"
ENV_PULL_WORKER_TOKEN = "RENGINE_WORKER_PULL_TOKEN"
ENV_PULL_SSL_VERIFY = "RENGINE_PULL_SSL_VERIFY"
ENV_PULL_POLL_INTERVAL = "RENGINE_PULL_POLL_INTERVAL"
ENV_PULL_JOB_TIMEOUT = "RENGINE_PULL_JOB_TIMEOUT"
ENV_PULL_MAX_CONSECUTIVE_FAILURES = "RENGINE_PULL_MAX_CONSECUTIVE_FAILURES"
ENV_PULL_FAILURE_BACKOFF_MAX_DELAY = "RENGINE_PULL_FAILURE_BACKOFF_MAX_DELAY"
ENV_PULL_SCRIPTS_DIR = "RENGINE_PULL_SCRIPTS_DIR"
ENV_PULL_PYTHON = "RENGINE_PULL_PYTHON"
ENV_PULL_RUNNER_SCRIPT = "RENGINE_PULL_RUNNER_SCRIPT"

# Shared defaults.
DEFAULT_PULL_COMMAND_RETENTION_SECONDS = 604800
DEFAULT_PULL_REVOKE_WAIT_SECONDS = 90
DEFAULT_PULL_COMMAND_POLL_INTERVAL_MIN_SECONDS = 0.5
DEFAULT_PULL_COMMAND_POLL_INTERVAL_MAX_SECONDS = 10.0
DEFAULT_PULL_COMMAND_POLL_JITTER_RATIO = 0.2
DEFAULT_PULL_TOKEN_MAX_LENGTH = 256

DEFAULT_PULL_POLL_INTERVAL = 5.0
DEFAULT_PULL_JOB_TIMEOUT = 86400
DEFAULT_PULL_MAX_CONSECUTIVE_FAILURES = 12
DEFAULT_PULL_FAILURE_BACKOFF_MAX_DELAY = 300.0
ENV_PULL_HTTP_TIMEOUT = "RENGINE_PULL_TIMEOUT"
DEFAULT_PULL_HTTP_TIMEOUT = 120.0

